# note:  these frequencies should be in a form that Rufus understands.  E.g., 5s
healthCreateFrequency: 5s
statCreateFrequency: 5s

healthyInterval: 20
engineMinRPMs: 0
engineMaxRPMs: 200

statRange: 6



